### ISSUE TITLE
Split Main into methods

### ISSUE THREAD

**Issue by Fliens** [Fliens/AutoCraft-Plugin#4]
The 'Autocraft' class should be cleaned up for better readability.
So multiple actions like collecting all autocrafters in a world or checking if there are enough items in an inventory

**Comment by MrTransistorsChannel** [comment]
There's no good way to check if there's enough space without trying to add items. #8 has a new method 

```java
private boolean addItemsIfCan(Inventory inventory, ArrayList<ItemStack> items){
		ItemStack[] mutableCont = inventory.getContents();
		ItemStack[] contents = inventory.getContents();
		for(int i = 0; i < mutableCont.length; i++) contents[i] = mutableCont[i] == null ? null : mutableCont[i].clone();
		for(ItemStack item : items){
			Map<Integer, ItemStack> left = inventory.addItem(item.clone());
			if(!left.isEmpty()){
				inventory.setStorageContents(contents);
				return false;
			}
		}
		return true;
	}
```
that technically does the same thing but also adds items if it can, this can be modified to test-add items and then revert everything back if it is really needed. I can implement testing in the next update if you want.

**Comment by Fliens** [comment]
> There's no good way to check if there's enough space without trying to add items. #8 has a new method
> 
> ```java
> private boolean addItemsIfCan(Inventory inventory, ArrayList<ItemStack> items){
> 		ItemStack[] mutableCont = inventory.getContents();
> 		ItemStack[] contents = inventory.getContents();
> 		for(int i = 0; i < mutableCont.length; i++) contents[i] = mutableCont[i] == null ? null : mutableCont[i].clone();
> 		for(ItemStack item : items){
> 			Map<Integer, ItemStack> left = inventory.addItem(item.clone());
> 			if(!left.isEmpty()){
> 				inventory.setStorageContents(contents);
> 				return false;
> 			}
> 		}
> 		return true;
> 	}
> ```
> 
> that technically does the same thing but also adds items if it can, this can be modified to test-add items and then revert everything back if it is really needed. I can implement testing in the next update if you want.

Sounds great

**Comment by MrTransistorsChannel** [comment]
Well, this can be probably closed now
