### ISSUE TITLE
Hoppers are able to move items in/from autocrafters

### ISSUE THREAD

**Issue by MrTransistorsChannel** [Fliens/AutoCraft-Plugin#6]
#### Description:
Ok so this may be not a bug but rather used as a toggleable feature.
If you place a hopper facing into an autocrafter/place a hopper underneath it it will be able to transfer items thus making it impossible to use it in vertical hopper lines or in some special cases when you can`t fit a chest into a contraption.

#### Possible fix: 
*Add a config option to enable changing the inventory of an autocrafter with a hopper* because it can be used as a way to automate recipe changing

Didn`t look into the ways of preventing it from happening, but I think it will be similar to the way we currently prevent items from being dispensed from crafters, can probably even be done with the same EventListener

**Comment by MrTransistorsChannel** [comment]
Will start working on this one after we resolve the #2 (#5 is fixing it but needs testing and project structure changes)

**Comment by Fliens** [comment]
Yeah you should be able to cancel the inventoryMove event
